### PR TITLE
Integrate SQLITE3 #12

### PR DESCRIPTION
**Pull request by liammcmanu**

### CODE REVIEW

**Comment by liammcmanu** [comment]
Cal it's time for the spell check, get a looking
Once you're good drop it on Kayla for final review

**Comment by liammcmanu** [comment]
^ Should probably add some of the test process to a doc

**Review by Callumator — APPROVED** [review]
Looks good to me. @k4ylZ137 your turn.

**Review by k4ylZ137 — APPROVED** [review]
Looks good to me, db initialisation should go smoothly.

**Pull request merged**
